
/* Criação da tabela exatamente igual a fonte de dados */
CREATE TABLE IF NOT EXISTS `STG_RECLAMACAO` (
  Ano bigint(15) DEFAULT NULL,
  Trimestre varchar(255) DEFAULT NULL,
  Categoria varchar(255) DEFAULT NULL,
  Tipo varchar(255) DEFAULT NULL,
  `CNPJ IF` bigint(15) DEFAULT NULL,
  `Instituição financeira`  varchar(255) DEFAULT NULL,
  `Índice` DECIMAL(10,2) DEFAULT NULL,
  `Quantidade de reclamações reguladas procedentes` bigint(15) DEFAULT NULL,
  `Quantidade de reclamações reguladas - outras` bigint(15) DEFAULT NULL,
  `Quantidade de reclamações não reguladas` bigint(15) DEFAULT NULL,
  `Quantidade total de reclamações` bigint(15) DEFAULT NULL,
  `Quantidade total de clientes – CCS e SCR` bigint(15) DEFAULT NULL,
  `Quantidade de clientes – CCS` bigint(15) DEFAULT NULL,
  `Quantidade de clientes – SCR` bigint(15) DEFAULT NULL
) 

/* Criação da tabela ODS, com padronização aplicada */

CREATE TABLE IF NOT EXISTS `ODS_RECLAMACAO` (
  ANO bigint(15) DEFAULT NULL,
  TRIMESTRE varchar(255) DEFAULT NULL,
  CATEGORIA varchar(255) DEFAULT NULL,
  TIPO varchar(255) DEFAULT NULL,
  CNPJ bigint(15) DEFAULT NULL,
  INSTITUICAO varchar(255) DEFAULT NULL,
  INDICE DECIMAL(10,2) DEFAULT NULL,
  QTD_RECLAMACOES_PROCEDENTES bigint(15) DEFAULT NULL,
  QTD_RECLAMACOES_OUTRAS bigint(15) DEFAULT NULL,
  QTD_RECLAMACOES_NAO_REGULADAS bigint(15) DEFAULT NULL,
  QTD_RECLAMACOES bigint(15) DEFAULT NULL,
  QTD_CLIENTES bigint(15) DEFAULT NULL,
  QTD_CLIENTES_CCS bigint(15) DEFAULT NULL,
  QTD_CLIENTES_SCR bigint(15) DEFAULT NULL,
  SK_RECLAMACAO	INT,
  CONSTRAINT SK_RECLAMACAO PRIMARY KEY (SK_RECLAMACAO)
) 

/* criação da tabela STG de tarifas bancarias */
CREATE TABLE IF NOT EXISTS `STG_TARIFAS_BANCARIAS` (
  STRING_CNPJ 		varchar(500) 	DEFAULT NULL,
  CODIGO_SERVICO 	varchar(255) 	DEFAULT NULL,
  SERVICO 			varchar(255) 	DEFAULT NULL,
  UNIDADE 			varchar(255) 	DEFAULT NULL,
  DATA_VIGENCIA 	date 			DEFAULT NULL,
  VALOR_MAXIMO 		DECIMAL(10,2) 	DEFAULT NULL,
  TIPO_VALOR 		varchar(255) 	DEFAULT NULL,
  PERIODICIDADE 	varchar(255) 	DEFAULT NULL
)

/* criação da tabela ODS de tarifas bancarias */
CREATE TABLE IF NOT EXISTS `ODS_TARIFAS_BANCARIAS` (
  CNPJ 		varchar(500) 	DEFAULT NULL,
  CODIGO_SERVICO 	varchar(255) 	DEFAULT NULL,
  SERVICO 			varchar(255) 	DEFAULT NULL,
  UNIDADE 			varchar(255) 	DEFAULT NULL,
  DATA_VIGENCIA 	date 			DEFAULT NULL,
  VALOR_MAXIMO 		DECIMAL(10,2) 	DEFAULT NULL,
  TIPO_VALOR 		varchar(255) 	DEFAULT NULL,
  PERIODICIDADE 	varchar(255) 	DEFAULT NULL,
  SK_TARIFAS	INT,
  CONSTRAINT SK_TARIFAS PRIMARY KEY (SK_TARIFAS)
)


/* Exemplo de tratamento efetuado na ODS, mas foi feito diretamente no ETL. Essa querie trata-se
	apenas de um exemplo de carga */
    
insert into ODS_TARIFAS_BANCARIAS (CNPJ
	,CODIGO_SERVICO 
	,SERVICO 
	,UNIDADE
	,DATA_VIGENCIA 
	,VALOR_MAXIMO 
	,TIPO_VALOR 
	,PERIODICIDADE)

SELECT
	 CAST(REPLACE(REPLACE(REPLACE(RIGHT(STRING_CNPJ,10),"'",""),"=",""),"J","") AS SIGNED)  AS CNPJ
	,CODIGO_SERVICO 
	,SERVICO 
	,UNIDADE
	,DATA_VIGENCIA 
	,VALOR_MAXIMO 
	,TIPO_VALOR 
	,PERIODICIDADE
FROM STG_TARIFAS_BANCARIAS;

/* DIM SERVICO */

CREATE TABLE IF NOT EXISTS `DIM_SERVICO` (
  CODIGO_SERVICO 	INT,
  SERVICO 			varchar(255) 	DEFAULT NULL,
  CONSTRAINT CODIGO_SERVICO PRIMARY KEY (CODIGO_SERVICO)
); 

/* DIM UNIDADE */

CREATE TABLE DIM_UNIDADE
( 
  CODIGO_UNIDADE INT NOT NULL AUTO_INCREMENT,
  UNIDADE VARCHAR(255) DEFAULT NULL,
  CONSTRAINT CODIGO_UNIDADE PRIMARY KEY (CODIGO_UNIDADE)
);


/* DIM INSTITUICAO */

CREATE TABLE DIM_INSTITUICAO
( 
  CODIGO_INSTITUICAO INT NOT NULL AUTO_INCREMENT,
  INSTITUICAO VARCHAR(255) DEFAULT NULL,
  TIPO VARCHAR(255) DEFAULT NULL,
  CONSTRAINT CODIGO_INSTITUICAO PRIMARY KEY (CODIGO_INSTITUICAO)
);

/* DIM TEMPO */

CREATE TABLE DIM_TEMPO
( 
  ANO INT NOT NULL ,
  TRIMESTRE VARCHAR(255) DEFAULT NULL,
  CODIGO_TEMPO INT,
  CONSTRAINT CODIGO_TEMPO PRIMARY KEY (CODIGO_TEMPO)
);

/* CRIA FATO RECL */
CREATE TABLE FATO_RECL (
  CODIGO_TEMPO INT,
  CNPJ INT,
  CODIGO_INSTITUICAO INT,
  INDICE NUMERIC(10,2),
  QTD_RECLAMACOES_PROCEDENTES INT,
  QTD_RECLAMACOES_OUTRAS INT,
  QTD_RECLAMACOES_NAO_REGULADAS INT,
  QTD_RECLAMACOES INT,
  QTD_CLIENTES INT,
  QTD_CLIENTES_CCS INT,
  QTD_CLIENTES_SCR INT,
  SK_FATO_RECL INT,
  CONSTRAINT SK_FATO_RECL PRIMARY KEY (SK_FATO_RECL),
     FOREIGN KEY (CODIGO_TEMPO) REFERENCES DIM_TEMPO(CODIGO_TEMPO),
     FOREIGN KEY (CODIGO_INSTITUICAO) REFERENCES DIM_INSTITUICAO(CODIGO_INSTITUICAO)
 );	
 
 /* CRIA FATO TARIFAS */
 
 CREATE TABLE FATO_TARIFAS (
  CNPJ int DEFAULT NULL,
  CODIGO_SERVICO int DEFAULT NULL,
  CODIGO_UNIDADE int DEFAULT NULL,
  DATA_VIGENCIA date DEFAULT NULL,
  VALOR_MAXIMO decimal(10,2) DEFAULT NULL,
  CODIGO_TIPO_VALOR int DEFAULT NULL,
  SK_FATO_TARIFAS INT,
  CONSTRAINT SK_FATO_TARIFAS PRIMARY KEY (SK_FATO_TARIFAS),
  FOREIGN KEY (CODIGO_SERVICO) REFERENCES DIM_SERVICO(CODIGO_SERVICO),
  FOREIGN KEY (CODIGO_UNIDADE) REFERENCES DIM_UNIDADE(CODIGO_UNIDADE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;






 